first.insertAdjacentHTML('beforebegin', '<div class="text">beforebegin</div>')
first.insertAdjacentHTML('beforeend', '<div class="text">beforeend</div>')
first.insertAdjacentHTML('afterbegin', '<div class="text">afterbegin</div >')
first.insertAdjacentHTML('afterend','<div class="text">afterend</div>')
first.remove()